In [13]:
#https://machinelearningmastery.com/how-to-develop-a-generative-adversarial-network-for-a-1-dimensional-function-from-scratch-in-keras/

In [51]:
import pandas as pd 
import numpy as np

In [42]:
# read in excel with techniques and probabilities, sheet X removed latest 20%
X = pd.read_excel("../Data for algorithms.xlsx", sheet_name="X", index_col="ID").drop("created", axis=1).drop("prop", axis=0)
X

T1548.002  T1134  T1134.002  T1134.001  T1087.002  T1087.003  \
ID                                                                    
S0066        0.0    0.0        0.0        0.0        0.0        0.0   
S0002        0.0    0.0        0.0        0.0        0.0        0.0   
S0051        0.0    0.0        0.0        0.0        0.0        0.0   
S0083        0.0    0.0        0.0        0.0        0.0        0.0   
S0080        0.0    0.0        0.0        0.0        0.0        0.0   
...          ...    ...        ...        ...        ...        ...   
S0465        0.0    0.0        0.0        0.0        0.0        0.0   
S0466        0.0    0.0        0.0        0.0        0.0        0.0   
S0467        0.0    0.0        0.0        0.0        0.0        0.0   
S0468        0.0    0.0        0.0        0.0        0.0        0.0   
S0472        0.0    0.0        0.0        0.0        0.0        0.0   

       T1087.001  T1071  T1071.004  T1071.002  ...  T1078.003  T1125  T1497  \
ID                                             ...                            
S0066        0.0    0.0        0.0        0.0  ...        0.0    0.0    0.0   
S0002        0.0    0.0        0.0        0.0  ...        0.0    0.0    0.0   
S0051        0.0    0.0        0.0        0.0  ...        0.0    0.0    0.0   
S0083        0.0    0.0        0.0        0.0  ...        0.0    0.0    0.0   
S0080        0.0    0.0        0.0        0.0  ...        0.0    0.0    0.0   
...          ...    ...        ...        ...  ...        ...    ...    ...   
S0465        0.0    0.0        0.0        1.0  ...        0.0    0.0    0.0   
S0466        0.0    0.0        0.0        0.0  ...        0.0    0.0    0.0   
S0467        0.0    0.0        0.0        0.0  ...        0.0    1.0    0.0   
S0468        0.0    0.0        0.0        0.0  ...        0.0    0.0    0.0   
S0472        0.0    0.0        0.0        0.0  ...        0.0    0.0    0.0   

       T1497.001  T1497.003  T1102  T1102.002  T1102.001  T1102.003  T1047  
ID                                                                          
S0066        0.0        0.0    0.0        0.0        0.0        0.0    0.0  
S0002        0.0        0.0    0.0        0.0        0.0        0.0    0.0  
S0051        0.0        0.0    0.0        0.0        1.0        0.0    0.0  
S0083        0.0        0.0    0.0        0.0        0.0        0.0    0.0  
S0080        0.0        0.0    0.0        0.0        0.0        0.0    0.0  
...          ...        ...    ...        ...        ...        ...    ...  
S0465        0.0        0.0    0.0        0.0        0.0        0.0    0.0  
S0466        0.0        0.0    0.0        0.0        0.0        0.0    0.0  
S0467        0.0        0.0    0.0        0.0        0.0        0.0    0.0  
S0468        0.0        0.0    0.0        0.0        0.0        0.0    0.0  
S0472        0.0        0.0    0.0        0.0        0.0        0.0    0.0  

[358 rows x 192 columns]

In [117]:
# read in excel with newest 20 percent of techniques for evaluation
y_train = pd.read_excel("../Data for algorithms.xlsx", sheet_name="Y", index_col="ID")
y_train = y_train.drop(y_train.tail(2).index, axis=0)
y_train = y_train.drop(['created'], axis = 1).T
y_train

ID         S0471  S0470  S0469  S0473  S0475  S0477  S0476  S0481  S0482  \
T1548.002      0      0      0      0      0      0      0      0      0   
T1134          0      0      0      0      0      0      0      0      0   
T1134.002      0      0      0      0      0      0      0      0      0   
T1134.001      0      0      0      0      0      0      0      0      0   
T1087.002      0      0      0      0      0      0      1      0      0   
...          ...    ...    ...    ...    ...    ...    ...    ...    ...   
T1102          0      0      0      0      0      0      0      0      0   
T1102.002      0      0      0      0      0      0      0      0      0   
T1102.001      0      0      0      0      0      0      0      0      0   
T1102.003      0      0      0      0      0      0      0      0      0   
T1047          0      0      0      0      0      0      1      0      0   

ID         S0483  ...  S0590  S0593  S0591  S0592  S0595  S0594  S0596  S0597  \
T1548.002      0  ...      0      0      0      0      0      0      0      0   
T1134          0  ...      0      0      0      0      0      0      0      0   
T1134.002      0  ...      0      0      0      0      0      0      0      0   
T1134.001      0  ...      0      0      0      0      0      0      0      0   
T1087.002      1  ...      0      0      0      0      0      0      0      0   
...          ...  ...    ...    ...    ...    ...    ...    ...    ...    ...   
T1102          0  ...      0      0      0      0      0      0      0      0   
T1102.002      0  ...      0      0      0      0      0      0      0      0   
T1102.001      0  ...      0      0      0      0      0      0      0      0   
T1102.003      0  ...      0      0      0      0      0      0      0      0   
T1047          1  ...      0      0      0      0      0      0      0      0   

ID         S0599  S0600  
T1548.002      0      0  
T1134          0      0  
T1134.002      0      0  
T1134.001      0      0  
T1087.002      0      0  
...          ...    ...  
T1102          0      1  
T1102.002      0      0  
T1102.001      0      0  
T1102.003      0      0  
T1047          0      0  

[192 rows x 89 columns]

In [46]:

# example of generating random samples from X^2
from numpy.random import rand
from numpy import hstack
from matplotlib import pyplot

# generate randoms sample from x^2
def generate_samples(n=50):
    """# generate random inputs in [-0.5, 0.5]
    X1 = rand(n) - 0.5
    # generate outputs X^2 (quadratic)
    X2 = X1 * X1
    # stack arrays
    X1 = X1.reshape(n, 1)
    X2 = X2.reshape(n, 1)
    return hstack((X1, X2))"""
    
    # return here random sample of X_small
    return X.sample(n).T # return n software  192 x n

# generate samples
data = generate_samples()

print(type(data), data.shape)
data

<class 'pandas.core.frame.DataFrame'> (192, 50)


ID         S0124  S0083  S0115  S0039  S0395  S0381  S0058  S0064  S0004  \
T1548.002    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
T1134        0.0    0.0    0.0    0.0    0.0    0.0    1.0    0.0    0.0   
T1134.002    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
T1134.001    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
T1087.002    0.0    0.0    0.0    1.0    0.0    0.0    0.0    0.0    0.0   
...          ...    ...    ...    ...    ...    ...    ...    ...    ...   
T1102        0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
T1102.002    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
T1102.001    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
T1102.003    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
T1047        0.0    0.0    0.0    0.0    0.0    1.0    0.0    0.0    0.0   

ID         S0226  ...  S0276  S0020  S0072  S0031  S0157  S0340  S0414  S0446  \
T1548.002    0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
T1134        0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    1.0   
T1134.002    0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
T1134.001    0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
T1087.002    0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
...          ...  ...    ...    ...    ...    ...    ...    ...    ...    ...   
T1102        0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
T1102.002    0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
T1102.001    0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
T1102.003    0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
T1047        0.0  ...    0.0    0.0    0.0    0.0    0.0    1.0    0.0    0.0   

ID         S0055  S0018  
T1548.002    0.0    0.0  
T1134        0.0    0.0  
T1134.002    0.0    0.0  
T1134.001    0.0    0.0  
T1087.002    0.0    1.0  
...          ...    ...  
T1102        0.0    0.0  
T1102.002    0.0    0.0  
T1102.001    0.0    0.0  
T1102.003    0.0    0.0  
T1047        0.0    0.0  

[192 rows x 50 columns]

In [47]:
# define the discriminator model
from keras.models import Sequential
from keras.layers import Dense
from keras.utils.vis_utils import plot_model

# define the standalone discriminator model
def define_discriminator(n_inputs=2):
	model = Sequential()
	model.add(Dense(25, activation='relu', kernel_initializer='he_uniform', input_dim=n_inputs))
	model.add(Dense(1, activation='sigmoid'))
	# compile model
	model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
	return model

# define the discriminator model
model = define_discriminator()
# summarize the model
model.summary()
# plot the model
plot_model(model, to_file='discriminator_plot.png', show_shapes=True, show_layer_names=True)

Model: "sequential_12"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_20 (Dense)             (None, 25)                75        
_________________________________________________________________
dense_21 (Dense)             (None, 1)                 26        
Total params: 101
Trainable params: 101
Non-trainable params: 0
_________________________________________________________________
('You must install pydot (`pip install pydot`) and install graphviz (see instructions at https://graphviz.gitlab.io/download/) ', 'for plot_model/model_to_dot to work.')


In [56]:
# generate n real samples with class labels
def generate_real_samples(n):
    T = X.shape[1]
    X_real = np.asarray(X.sample(n)).reshape((n,T)) # return n software  192 x n
    # generate class labels
    y_real = ones((n, 1))
    # return array of real software vectors and y as label 1 because all are real
    return X_real, y_real
generate_real_samples(3)

(array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
         1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0

In [48]:
generate_real_samples(3)

(array([[-0.45513197,  0.20714511],
        [ 0.20455119,  0.04184119],
        [ 0.49504653,  0.24507106]]),
 array([[1.],
        [1.],
        [1.]]))

In [68]:
# generate n fake samples with class labels
def generate_fake_samples(n):
    T = X.shape[1]
    probForOne = 12.5/T
    X_fake = np.random.choice([0,1], size=(n,T), p=[1 - probForOne, probForOne])
    y_fake = zeros((n, 1))
    return X_fake, y_fake
generate_fake_samples(2)

(array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
         1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [60]:
generate_fake_samples(2)

(array([[ 0.51896933, -0.69225249],
        [ 0.65826679,  0.83359889]]),
 array([[0.],
        [0.]]))

In [70]:
# define and fit a discriminator model
from numpy import zeros
from numpy import ones
from numpy import hstack
from numpy.random import rand
from numpy.random import randn
from keras.models import Sequential
from keras.layers import Dense

# define the standalone discriminator model
def define_discriminator(n_inputs=2):
	model = Sequential()
	model.add(Dense(25, activation='relu', kernel_initializer='he_uniform', input_dim=n_inputs))
	model.add(Dense(1, activation='sigmoid'))
	# compile model
	model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
	return model

# generate n real samples with class labels
def generate_real_samples(n):
    T = X.shape[1]
    X_real = np.asarray(X.sample(n)).reshape((n,T)) # return n software  192 x n
    # generate class labels
    y_real = ones((n, 1))
    # return array of real software vectors and y as label 1 because all are real
    return X_real, y_real

# generate n fake samples with class labels
def generate_fake_samples(n):
    T = X.shape[1]
    probForOne = 12.5/T
    X_fake = np.random.choice([0,1], size=(n,T), p=[1 - probForOne, probForOne])
    y_fake = zeros((n, 1))
    return X_fake, y_fake

# train the discriminator model
def train_discriminator(model, n_epochs=100, n_batch=32):
	half_batch = int(n_batch / 2)
	# run epochs manually
	for i in range(n_epochs):
		# generate real examples
		X_real, y_real = generate_real_samples(half_batch)
		# update model
		model.train_on_batch(X_real, y_real)
		# generate fake examples
		X_fake, y_fake = generate_fake_samples(half_batch)
		# update model
		model.train_on_batch(X_fake, y_fake)
		# evaluate the model
		_, acc_real = model.evaluate(X_real, y_real, verbose=0)
		_, acc_fake = model.evaluate(X_fake, y_fake, verbose=0)
		print(i, acc_real, acc_fake)

# define the discriminator model
model = define_discriminator(X.shape[1])
# fit the model
train_discriminator(model)

0 0.3125 0.875
1 0.25 0.75
2 0.3125 0.6875
3 0.5625 0.6875
4 0.5625 0.875
5 0.625 0.8125
6 0.5625 0.9375
7 0.5 0.9375
8 0.5 0.875
9 0.625 1.0
10 0.5625 0.9375
11 0.4375 0.8125
12 0.5 0.875
13 0.625 0.9375
14 0.625 0.9375
15 0.8125 0.9375
16 0.625 1.0
17 0.8125 0.8125
18 0.75 1.0
19 0.6875 0.875
20 0.875 1.0
21 0.75 0.9375
22 0.75 0.9375
23 0.8125 0.9375
24 0.6875 0.875
25 0.9375 1.0
26 0.8125 1.0
27 0.8125 1.0
28 0.75 0.9375
29 0.75 0.9375
30 0.875 0.9375
31 0.875 1.0
32 0.875 0.9375
33 0.75 1.0
34 0.5 1.0
35 0.875 1.0
36 0.8125 1.0
37 0.6875 1.0
38 0.9375 0.9375
39 0.625 1.0
40 0.75 1.0
41 0.875 0.9375
42 0.8125 0.9375
43 0.875 1.0
44 0.5625 1.0
45 0.75 1.0
46 0.8125 0.9375
47 0.8125 1.0
48 0.8125 0.9375
49 0.6875 1.0
50 0.9375 1.0
51 0.8125 0.9375
52 0.875 1.0
53 0.9375 1.0
54 0.6875 1.0
55 0.9375 0.75
56 0.9375 0.9375
57 1.0 0.9375
58 0.875 1.0
59 0.875 1.0
60 0.875 1.0
61 0.875 1.0
62 0.9375 1.0
63 0.75 1.0
64 0.75 0.9375
65 0.6875 0.9375
66 0.9375 0.9375
67 0.9375 0.9375
68 0.8125

In [107]:
# demonstrate creating the three models in the gan
from keras.models import Sequential
from keras.layers import Dense
from keras.utils.vis_utils import plot_model

# define the standalone discriminator model
def define_discriminator(n_inputs=2):
    model = Sequential()
    model.add(Dense(25, activation='relu', kernel_initializer='he_uniform', input_dim=n_inputs))
    #model.add(Dense(15, activation='relu', kernel_initializer='he_uniform', input_dim=n_inputs))
    model.add(Dense(1, activation='sigmoid'))
    # compile model
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

# define the standalone generator model
def define_generator(latent_dim, n_outputs=2):
    model = Sequential()
    model.add(Dense(15, activation='relu', kernel_initializer='he_uniform', input_dim=latent_dim))
    model.add(Dense(n_outputs, activation='linear'))
    return model

# define the combined generator and discriminator model, for updating the generator
def define_gan(generator, discriminator):
	# make weights in the discriminator not trainable
	discriminator.trainable = False
	# connect them
	model = Sequential()
	# add generator
	model.add(generator)
	# add the discriminator
	model.add(discriminator)
	# compile model
	model.compile(loss='binary_crossentropy', optimizer='adam')
	return model

# size of the latent space
latent_dim = 50 #later 300
# create the discriminator
discriminator = define_discriminator(X.shape[1])
# create the generator
generator = define_generator(latent_dim, X.shape[1])
# create the gan
gan_model = define_gan(generator, discriminator)
# summarize gan model
gan_model.summary()
# plot gan model
plot_model(gan_model, to_file='gan_plot.png', show_shapes=True, show_layer_names=True)

Model: "sequential_60"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
sequential_59 (Sequential)   (None, 192)               3837      
_________________________________________________________________
sequential_58 (Sequential)   (None, 1)                 4851      
Total params: 8,688
Trainable params: 3,837
Non-trainable params: 4,851
_________________________________________________________________
('You must install pydot (`pip install pydot`) and install graphviz (see instructions at https://graphviz.gitlab.io/download/) ', 'for plot_model/model_to_dot to work.')


In [77]:
# generate points in latent space as input for the generator
def generate_latent_points(latent_dim, n):
	# generate points in the latent space
	x_input = randn(latent_dim * n)
	# reshape into a batch of inputs for the network
	x_input = x_input.reshape(n, latent_dim)
	return x_input

In [161]:
# use the generator to generate n fake examples, with class labels
def generate_fake_samples(generator, latent_dim, n):
    # generate points in latent space
    x_input = generate_latent_points(latent_dim, n)
    # predict outputs
    X = np.asarray(generator.predict(x_input)).round()
    X = np.where(X > 0.5, 1, 0)
    # create class labels
    y = zeros((n, 1))
    return X, y

In [158]:
a = np.array([-0.3, 0.4, 0.9, 0.2])
np.where(a > 0.5, 1, 0)

array([0, 0, 1, 0])

In [81]:
# evaluate the discriminator and plot real and fake points
def summarize_performance(epoch, generator, discriminator, latent_dim, n=100):
	# prepare real samples
	x_real, y_real = generate_real_samples(n)
	# evaluate discriminator on real examples
	_, acc_real = discriminator.evaluate(x_real, y_real, verbose=0)
	# prepare fake examples
	x_fake, y_fake = generate_fake_samples(generator, latent_dim, n)
	# evaluate discriminator on fake examples
	_, acc_fake = discriminator.evaluate(x_fake, y_fake, verbose=0)
	# summarize discriminator performance
	print(epoch, acc_real, acc_fake)
	# scatter plot real and fake data points
	#pyplot.scatter(x_real[:, 0], x_real[:, 1], color='red')
	#pyplot.scatter(x_fake[:, 0], x_fake[:, 1], color='blue')
	#pyplot.show()

In [137]:
# train the generator and discriminator
def train(g_model, d_model, gan_model, latent_dim, n_epochs=2000, n_batch=64, n_eval=200):
	# determine half the size of one batch, for updating the discriminator
	half_batch = int(n_batch / 2)
	# manually enumerate epochs
	for i in range(n_epochs):
		# prepare real samples
		x_real, y_real = generate_real_samples(half_batch)
		# prepare fake examples
		x_fake, y_fake = generate_fake_samples(g_model, latent_dim, half_batch)
		# update discriminator
		d_model.train_on_batch(x_real, y_real)
		d_model.train_on_batch(x_fake, y_fake)
		# prepare points in latent space as input for the generator
		x_gan = generate_latent_points(latent_dim, n_batch)
		# create inverted labels for the fake samples
		y_gan = ones((n_batch, 1))
		# update the generator via the discriminator's error
		gan_model.train_on_batch(x_gan, y_gan)
		# evaluate the model every n_eval epochs
		if (i+1) % n_eval == 0:
			summarize_performance(i, g_model, d_model, latent_dim)

In [162]:
# size of the latent space
latent_dim = 50
# create the discriminator
discriminator = define_discriminator(X.shape[1])
# create the generator
generator = define_generator(latent_dim, X.shape[1])
# create the gan
gan_model = define_gan(generator, discriminator)
# train model
train(generator, discriminator, gan_model, latent_dim)

199 0.5199999809265137 0.7300000190734863
399 0.7799999713897705 0.7699999809265137
599 0.7599999904632568 0.8600000143051147
799 0.6100000143051147 0.6200000047683716
999 0.8799999952316284 0.9100000262260437
1199 0.8999999761581421 0.8100000023841858
1399 0.8100000023841858 0.6299999952316284
1599 0.8399999737739563 0.8899999856948853
1799 0.9100000262260437 0.9300000071525574
1999 0.8299999833106995 0.949999988079071


In [163]:
X_generated, y_generated = generate_fake_samples(generator, 50, 10)


In [164]:
newData = pd.DataFrame(X_generated).T
newData

0  1  2  3  4  5  6  7  8  9
0    0  0  0  0  1  0  0  0  0  0
1    0  0  0  0  0  0  0  0  0  0
2    0  0  0  0  0  0  0  0  0  0
3    0  0  0  0  0  0  0  0  0  0
4    0  0  0  0  0  0  0  0  0  0
..  .. .. .. .. .. .. .. .. .. ..
187  0  0  0  0  0  0  0  0  0  0
188  0  0  0  0  1  0  0  0  0  0
189  0  0  0  0  0  0  0  0  0  0
190  0  0  0  0  0  0  0  0  0  0
191  0  0  0  0  1  0  0  0  0  0

[192 rows x 10 columns]

In [165]:
newData.to_excel("first_test_with_np_where.xlsx")

In [116]:
# read in the y_train data set and the predicted software

def calculate_F_score(y_train: pd.DataFrame, predicted_sw: np.array, do_print=False):    
    #print(type(y_train), type(predicted_sw))
    assert y_train.shape[0] == predicted_sw.shape[0]
    
    ones = np.ones(len(y_train))

    occurences = np.array(predicted_sw).T @ ones
    
    F1_list = []
    Software_index = 0
    
    for software in y_train.columns:
        sum_s = y_train[software] @ predicted_sw

        precision = 0
        if occurences != 0:
            precision = sum_s/occurences
        
        number_of_techniques_y = y_train[software] @ ones
        recall = 0
        if number_of_techniques_y != 0:
            recall = sum_s/(number_of_techniques_y)
        F1 = 0
        if (precision + recall) != 0:
            F1 = 2 * precision* recall /(precision + recall)
            
        F1_list.append(F1)
    
    return max(F1_list), F1_list.index(max(F1_list)) ,predicted_sw

In [166]:
for software in newData.columns:
    
    F1, F1Index, _ = calculate_F_score(y_train, np.array(newData[software]))
    print(F1, F1Index)

0.42857142857142855 58
0.5 58
0.4242424242424242 43
0.3636363636363636 21
0.5263157894736842 58
0.3157894736842105 61
0.31249999999999994 35
0.4375 43
0.5 49
0.5454545454545454 58


In [168]:
examples_to_save = 20
df_to_save = pd.DataFrame([])
F1_values = pd.DataFrame([])
maxIndexValues = pd.DataFrame([])


for j in range(4):
    # size of the latent space
    latent_dim = 50
    # create the discriminator
    discriminator = define_discriminator(X.shape[1])
    # create the generator
    generator = define_generator(latent_dim, X.shape[1])
    # create the gan
    gan_model = define_gan(generator, discriminator)
    # train model
    train(generator, discriminator, gan_model, latent_dim)

    for i in range(examples_to_save):




        X_generated, y_generated = generate_fake_samples(generator, 50, 1)
        F1, maxIndex, generated_software = calculate_F_score(y_train, np.array(X_generated[0]))

        df_to_save[f"software_{j}{i}"] = generated_software
        print(F1)
        F1_values[f"software_{j}{i}"] = np.array([F1])
        maxIndexValues[f"software_{j}{i}"] = np.array([maxIndex])

print("")
print(pd.DataFrame(F1_values).T[0].describe()[1])
maxIndexValues

199 0.5899999737739563 0.7699999809265137
399 0.8700000047683716 0.9100000262260437
599 0.8399999737739563 0.8799999952316284
799 0.699999988079071 0.7400000095367432
999 0.8999999761581421 0.699999988079071
1199 0.8899999856948853 0.8799999952316284
1399 0.8299999833106995 0.8899999856948853
1599 0.8799999952316284 0.8500000238418579
1799 0.8999999761581421 0.8100000023841858
1999 0.9100000262260437 0.949999988079071
0.36363636363636365
0.4
0.5454545454545454
0.45454545454545453
0.4
0.4615384615384615
0.4
0.5454545454545454
0.5333333333333333
0.5333333333333333
0.5714285714285715
0.36363636363636365
0.5
0.47619047619047616
0.4
0.42857142857142855
0.4
0.4000000000000001
0.5
0.4000000000000001
199 0.5699999928474426 0.699999988079071
399 0.6899999976158142 0.7200000286102295
599 0.8500000238418579 0.9100000262260437
799 0.8100000023841858 0.7099999785423279
999 0.9200000166893005 0.8299999833106995
1199 0.7900000214576721 0.7200000286102295
1399 0.8700000047683716 0.9300000071525574
159

software_00  software_01  software_02  software_03  software_04  \
0           82           86            1           63           21   

   software_05  software_06  software_07  software_08  software_09  ...  \
0           21           86           55            1           47  ...   

   software_310  software_311  software_312  software_313  software_314  \
0            21            64            30            84            23   

   software_315  software_316  software_317  software_318  software_319  
0            43            58            58            25            80  

[1 rows x 80 columns]

In [143]:
df_to_save.to_excel("good_result.xlsx")

In [169]:
df_to_save.append(F1_values).append(maxIndexValues).to_excel('output3.xlsx')